homepage: "https://github.com/syncthing/syncthing"
language: go
primary_contact: "secsys-go@hotmail.com"
main_repo: "https://github.com/syncthing/syncthing"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
